name: Build Skia Library
on: workflow_dispatch
jobs:
  Build-for-windows:
    name: build-for-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6 
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
        
  
  
